### ISSUE TITLE
[REQ] Leon preheat

### ISSUE THREAD

**Issue by trizz** [jesperweiland/tesla-preheat#3]
I would like to use this tool with a Seat Leon.

**Comment by styxit** [comment]
+1 :+1: Also my house and my bed

**Comment by rvdh** [comment]
Seconded!

**Comment by robbinjanssen** [comment]
You have to install a module called 'garage.py'

**Comment by trizz** [comment]
@robbinjanssen I don't have room for that module anymore :disappointed:
